[WIP] Surface GPU support in qsimcirq
quantumlib/qsim pull request #398
Opened 2021-08-05 15:55 UTC by 95-martin-orion

This PR will allow qsimcirq users to request simulation on GPU resources.

2021-08-13 21:41 UTC, 95-martin-orion commented
This PR is now ready for review. Main components include:
* Added CUDA pybind module
* Modified existing pybind to work with both CPU and GPU
* Updated Makefile to build CUDA module if NVCC is available
* Added `QSimOptions` to contain Python simulator options
* Testing for GPU (verified on system w/GPU; skipped if unavailable)

Users with an NVIDIA GPU and the CUDA toolkit can make use of this feature by:
* Compiling qsim locally to enable GPU support
* Creating a qsimcirq.Simulator with `QSimOptions(use_gpu=True)`
* Executing circuits with that simulator

Known issues:
* Simulating expectation values can fail if the observables are composed of 1-qubit gates; this will cause the GPU expectation value test to fail. Observables on 2+ qubits should be unaffected.

2021-08-16 19:02 UTC, 95-martin-orion commented
The "known issue" was resolved in #409.

2021-08-17 16:05 UTC, sergeisakov requested changes
Thank you! It looks good. There are just a few small issues.

2021-08-17 16:11 UTC, sergeisakov commented
> Known issues:
> 
> * Simulating expectation values can fail if the observables are composed of 1-qubit gates; this will cause the GPU expectation value test to fail. Observables on 2+ qubits should be unaffected.

Could you remove that?

2021-08-17 16:11 UTC, sergeisakov commented
qsimh_simulator.py is not updated to run on GPUs, right?

2021-08-17 18:18 UTC, 95-martin-orion reviewed
Addressed the quick fixes. Still need to verify on GPU and fix+test the `init_state` concern.

2021-08-17 18:21 UTC, 95-martin-orion commented
> qsimh_simulator.py is not updated to run on GPUs, right?

Correct, it remains CPU-only.

2021-08-17 18:55 UTC, 95-martin-orion commented on pybind_interface/pybind_main.cpp
> +    For(num_sim_threads).Run(input_vector.size(), f, ptr, state.get());
Done and done.

2021-08-17 20:36 UTC, sergeisakov approved these changes

2021-08-17 20:53 UTC, merged