Fix expectation values.
quantumlib/qsim pull request #578
Opened 2022-12-27 19:07 UTC by Hosseinberg

The coefficient of the identity operators is now included in the expectation value calculation. The following example uses three different methods to calculate the expectation value. qsimcirq discards the coefficient of the identity operator. This PR resolves this issue.

```python
import cirq
import qsimcirq

objs = [(1.5, 'IIIIIII'), (-0.3, 'XZXIXII')]
num_qubits = 7
moments = 9
density = 0.95
qubits = cirq.LineQubit.range(num_qubits)
cirq_circuit = cirq.testing.random_circuit(qubits=qubits,
                                      n_moments=moments,
                                      op_density=density)

hamiltonian = 0
for w, pauli in objs:
    pauli = pauli[::-1]
    hamiltonian += float(w) * cirq.PauliString(
        cirq.I(cirq.LineQubit(i)) if p == 'I' else
        cirq.X(cirq.LineQubit(i)) if p == 'X' else
        cirq.Y(cirq.LineQubit(i)) if p == 'Y' else
        cirq.Z(cirq.LineQubit(i)) if p == 'Z' else
        None  
        for i, p in enumerate(pauli))

energy_ham = hamiltonian.expectation_from_state_vector(
    state_vector= cirq.final_state_vector(cirq_circuit), 
    qubit_map={q: i for i, q in enumerate(qubits)},
    atol=0.01)

qsimSim = qsimcirq.QSimSimulator()
qsimcirq_result = qsimSim.simulate_expectation_values(cirq_circuit, hamiltonian) 

cirqSim = cirq.Simulator()
cirq_result = cirqSim.simulate_expectation_values(cirq_circuit, hamiltonian)  

print(f'energy_ham = {energy_ham}')
print(f'qsimcirq_result = {qsimcirq_result}')
print(f'cirq_result = {cirq_result}')
```

2023-01-03 20:43 UTC, Hosseinberg commented
@95-martin-orion I believe this is not a duplicate of #577 since even after cloning and building locally the issue still exists. However, the suggested commit [3841701](https://github.com/quantumlib/qsim/pull/578/commits/3841701a7c311f5f087d14cd1aded9edfcb704d8) will resolve the issue.

2023-01-03 21:01 UTC, 95-martin-orion requested changes
> @95-martin-orion I believe this is not a duplicate of #577 since even after cloning and building locally the issue still exists.

In that case, this seems reasonable to me. Could you also add a test to `qsimcirq_tests/qsimcirq_test.py` which demonstrates the case that fails with #577 but passes with this PR?

2023-01-05 06:05 UTC, Hosseinberg commented on lib/expect.h
> +    else if (str.ops.size() == 1) {
Fixed in [74f4b23](https://github.com/quantumlib/qsim/pull/578/commits/74f4b2378d215a519d029f1996aa20cedac92b84)

2023-01-05 06:07 UTC, Hosseinberg commented on lib/expect.h
> +    else if (str.ops.size() == 1) {
The test is added by [22a59f3](https://github.com/quantumlib/qsim/pull/578/commits/22a59f307d7b7c571b0f8b51452aa5400fb9546d)

2023-01-05 20:02 UTC, Hosseinberg commented
@95-martin-orion I'm getting an error in the formatting check. Which Python code formatter should I use to ensure that it passes the format check?

2023-01-05 20:51 UTC, 95-martin-orion commented
> @95-martin-orion I'm getting an error in the formatting check. Which Python code formatter should I use to ensure that it passes the format check?

Formatting is checked with [check/format-incremental](https://github.com/quantumlib/qsim/blob/master/check/format-incremental), which uses [`black~=22.3.0`](https://github.com/quantumlib/qsim/blob/11e8afadc7f03c1691c0e506b9620311b26be2d6/dev-requirements.txt#L1). It should be possible to run this script locally.

From the logs, it looks like there's trailing whitespace on the marked lines.

2023-01-06 16:32 UTC, 95-martin-orion approved these changes

2023-01-06 16:32 UTC, merged