Add support for AMD GPUs
quantumlib/qsim pull request #619
Opened 2023-08-18 18:50 UTC by jakurzak

2023-09-27 17:12 UTC, tanujkhattar commented
@jakurzak Can you please add a PR description ? 

@sergeisakov Can you take a look at this PR?

2023-10-05 15:40 UTC, sergeisakov requested changes
Thank you for adding support for AMD GPUs. I can't really test if it works or not. Nevertheless the PR looks good to me. Could you fix a few formatting issues? Could you also add some doc?

2023-10-09 20:20 UTC, jakurzak commented
Thank you for taking the time to look at the PR!
I am out of office this week and traveling overseas.
I'll do my best to address the comments ASAP when I'm back in office.

2023-10-16 18:45 UTC, jakurzak commented on lib/statespace_cuda.h
> +    ErrorCheck(cudaMemset(state.get(), 0, MinSize(state.num_qubits()) * sizeof(fp_type)));
Fixed

2023-10-16 18:45 UTC, jakurzak commented on pybind_interface/Makefile
> +	$(HIPCC) basic/pybind_main_basic.cpp -o $(QSIMLIB_BASIC) $(CXXFLAGS) $(PYBINDFLAGS_BASIC)
Mixing compilers produces a mismatch between Python and C++ data types.
E.g., there's an issue with casting a Python instance of type qsimcirq.qsim_avx2.Circuit to its corresponding C++ type.
`RuntimeError: Unable to cast Python instance of type <class 'qsimcirq.qsim_avx2.Circuit'> to C++ type 'qsim::Circuit<qsim::Gate<float, qsim::Cirq::GateKind> >'`

2023-10-16 18:46 UTC, jakurzak commented on lib/vectorspace_cuda.h
> +      cudaMemcpy(dest.get(), src.get(),
Fixed

2023-10-16 18:46 UTC, jakurzak commented on lib/vectorspace_cuda.h
> +      cudaMemcpy(dest, src.get(),
Fixed

2023-10-16 18:46 UTC, jakurzak commented on lib/vectorspace_cuda.h
> +      cudaMemcpy(dest.get(), src,
Fixed

2023-10-16 18:46 UTC, jakurzak commented on lib/vectorspace_cuda.h
> +      cudaMemcpy(dest.get(), src, sizeof(fp_type) * size, cudaMemcpyHostToDevice));
Fixed

2023-10-16 18:49 UTC, jakurzak commented
I fixed the style issues and commented on the use of HIPCC for CPU code when compiling Python bindings.
I'll be looking into documentation now.

2023-11-07 19:25 UTC, jakurzak commented
I added basic documentation for AMD GPU support.
I added detailed description to the PR.
Please let me know if anything else needs to be done before the PR can be accepted.

2023-11-08 16:43 UTC, sergeisakov commented on pybind_interface/Makefile
> +	$(HIPCC) basic/pybind_main_basic.cpp -o $(QSIMLIB_BASIC) $(CXXFLAGS) $(PYBINDFLAGS_BASIC)
Thanks. It makes sense.

2023-11-08 16:48 UTC, sergeisakov commented
> I added basic documentation for AMD GPU support. I added detailed description to the PR. Please let me know if anything else needs to be done before the PR can be accepted.

Thank you. Could you replace Qsim with qsim in `amd_gpu.md`? Could you also add something about how to install the build tools? Is it ROCm?

2023-11-08 17:29 UTC, jakurzak commented
> Thank you. Could you replace Qsim with qsim in `amd_gpu.md`? Could you also add something about how to install the build tools? Is it ROCm?

done

2023-11-09 13:24 UTC, sergeisakov approved these changes
LGTM

2023-11-09 14:37 UTC, jakurzak commented
Looks like it's getting hung up on the kokoro test.
Any clue why?

2023-11-09 15:09 UTC, 95-martin-orion commented
Hmm. Doesn't look like I can re-trigger the kokoro test specifically. Could you push a commit so Github picks up on it?

2023-11-09 15:21 UTC, jakurzak commented
No cuQuantum support in the AMD port, BTW, as there's no AMD equivalent.
The HIP port should not affect anything in the CUDA implementation, though.
Pushed a commit to re-trigger.

2023-11-09 20:56 UTC, jakurzak commented
@sergeisakov, @95-martin-orion, can you help move this forward?
Thanks in advance!

2023-11-09 21:49 UTC, merged